# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: '/baseball-girls-diary'
baseurl_posts_img: '/baseball-girls-diary/assets/images/posts/'
baseurl_featured_img: '/baseball-girls-diary/assets/images/hero/'
baseurl_featured_thumbnail: '/baseball-girls-diary/assets/images/thumbnail/'
baseurl_javascripts: '/baseball-girls-diary/assets/javascripts/'

# 网页的标题
title: "棒球少女博客馆"
# 网站的主标题
name: "沙马依乌的棒球日记"
description: "记录我和棒球的每一天"

url: site url
icon: your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus: disqus_shortname # get it on https://disqus.com/admin/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"

# 其它配置, 可忽略, 无需修改
permalink: /:title/

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
exclude: [ changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock ]
